### ISSUE TITLE
App is not running after last pr merge

### ISSUE THREAD

**Issue by saurabh190802** [Cryptonaline/Cryptonaline-App#46]
App is not running after this pr merge
#45 

Is it fine to use icons different from design ?
@Subhampreet  @sidmohanty11

_Originally posted by @saurabh190802 in https://github.com/Cryptonaline/Cryptonaline-App/issues/45#issuecomment-1083243081_

**Comment by sidmohanty11** [comment]
can you share a possible solution? and can we completely move to react native cli, which we discussed in the gmeet? if we can, please do the migration. Thank you

**Comment by saurabh190802** [comment]
solved #55
